// ******* AUTOMATICALLY GENERATED BY PyKokkos *******
#ifndef PK_FUNCTOR_NSTREAM_HPP
#define PK_FUNCTOR_NSTREAM_HPP

struct pk_functor_nstream {
  struct nstream_tag {};
  int scalar;
  Kokkos::View<double *, Kokkos::LayoutRight, Kokkos::HostSpace,
               Kokkos::Experimental::EmptyViewHooks>
      A_view;
  Kokkos::View<double *, Kokkos::LayoutRight, Kokkos::HostSpace,
               Kokkos::Experimental::EmptyViewHooks>
      B_view;
  Kokkos::View<double *, Kokkos::LayoutRight, Kokkos::HostSpace,
               Kokkos::Experimental::EmptyViewHooks>
      C_view;
  pk_functor_nstream(
      int scalar,
      Kokkos::View<double *, Kokkos::LayoutRight, Kokkos::HostSpace,
                   Kokkos::Experimental::EmptyViewHooks>
          A_view,
      Kokkos::View<double *, Kokkos::LayoutRight, Kokkos::HostSpace,
                   Kokkos::Experimental::EmptyViewHooks>
          B_view,
      Kokkos::View<double *, Kokkos::LayoutRight, Kokkos::HostSpace,
                   Kokkos::Experimental::EmptyViewHooks>
          C_view) : scalar(scalar), A_view(A_view), B_view(B_view), C_view(C_view) {
    };
  void operator()(const nstream_tag &, int i) const;
};

#endif