// ******* AUTOMATICALLY GENERATED BY PyKokkos *******
#ifndef PK_FUNCTOR_FINAL_INTEGRATE_HPP
#define PK_FUNCTOR_FINAL_INTEGRATE_HPP

struct pk_functor_final_integrate {
  struct final_integrate_tag {};
  double dtf;
  Kokkos::View<double **, Kokkos::LayoutRight, Kokkos::HostSpace,
               Kokkos::Experimental::EmptyViewHooks>
      v;
  Kokkos::View<double **, Kokkos::LayoutRight, Kokkos::HostSpace,
               Kokkos::Experimental::EmptyViewHooks>
      f;
  Kokkos::View<int *, Kokkos::LayoutRight, Kokkos::HostSpace,
               Kokkos::Experimental::EmptyViewHooks>
      type;
  Kokkos::View<double *, Kokkos::LayoutRight, Kokkos::HostSpace,
               Kokkos::Experimental::EmptyViewHooks>
      mass;

  pk_functor_final_integrate(
      double dtf,
      Kokkos::View<double **, Kokkos::LayoutRight,
                   Kokkos::HostSpace,
                   Kokkos::Experimental::EmptyViewHooks>
          v,
      Kokkos::View<double **, Kokkos::LayoutRight,
                   Kokkos::HostSpace,
                   Kokkos::Experimental::EmptyViewHooks>
          f,
      Kokkos::View<int *, Kokkos::LayoutRight,
                   Kokkos::HostSpace,
                   Kokkos::Experimental::EmptyViewHooks>
          type,
      Kokkos::View<double *, Kokkos::LayoutRight,
                   Kokkos::HostSpace,
                   Kokkos::Experimental::EmptyViewHooks>
          mass) : dtf(dtf), v(v), f(f), type(type), mass(mass) {
  };
  void operator()(const final_integrate_tag &,
                                  int i) const ;
};

#endif