// ******* AUTOMATICALLY GENERATED BY PyKokkos *******
#ifndef PK_FUNCTOR_FULLNEIGH_REDUCE_HPP
#define PK_FUNCTOR_FULLNEIGH_REDUCE_HPP

struct pk_functor_fullneigh_reduce {
  struct fullneigh_reduce_tag {};
  bool use_stackparams;
  Kokkos::View<double **, Kokkos::LayoutRight, Kokkos::HostSpace,
               Kokkos::Experimental::EmptyViewHooks>
      rnd_lj1;
  Kokkos::View<double **, Kokkos::LayoutRight, Kokkos::HostSpace,
               Kokkos::Experimental::EmptyViewHooks>
      rnd_lj2;
  Kokkos::View<double **, Kokkos::LayoutRight, Kokkos::HostSpace,
               Kokkos::Experimental::EmptyViewHooks>
      rnd_cutsq;
  Kokkos::View<int *, Kokkos::LayoutRight, Kokkos::HostSpace,
               Kokkos::Experimental::EmptyViewHooks>
      num_neighs_view;
  Kokkos::View<int **, Kokkos::LayoutRight,
               Kokkos::HostSpace,
               Kokkos::Experimental::EmptyViewHooks>
      neighs_view;
  Kokkos::View<double **, Kokkos::LayoutRight, Kokkos::HostSpace,
               Kokkos::Experimental::EmptyViewHooks>
      x;
  Kokkos::View<double **, Kokkos::LayoutRight, Kokkos::HostSpace,
               Kokkos::Experimental::EmptyViewHooks>
      f;
  Kokkos::View<int *, Kokkos::LayoutRight, Kokkos::HostSpace,
               Kokkos::Experimental::EmptyViewHooks>
      type;
  pk_functor_fullneigh_reduce(
      bool use_stackparams,
      Kokkos::View<double **, Kokkos::LayoutRight,
                   Kokkos::HostSpace,
                   Kokkos::Experimental::EmptyViewHooks>
          rnd_lj1,
      Kokkos::View<double **, Kokkos::LayoutRight,
                   Kokkos::HostSpace,
                   Kokkos::Experimental::EmptyViewHooks>
          rnd_lj2,
      Kokkos::View<double **, Kokkos::LayoutRight,
                   Kokkos::HostSpace,
                   Kokkos::Experimental::EmptyViewHooks>
          rnd_cutsq,
      Kokkos::View<int *, Kokkos::LayoutRight,
                   Kokkos::HostSpace,
                   Kokkos::Experimental::EmptyViewHooks>
          num_neighs_view,
      Kokkos::View<int **, Kokkos::LayoutRight,
                   Kokkos::HostSpace,
                   Kokkos::Experimental::EmptyViewHooks>
          neighs_view,
      Kokkos::View<double **, Kokkos::LayoutRight,
                   Kokkos::HostSpace,
                   Kokkos::Experimental::EmptyViewHooks>
          x,
      Kokkos::View<double **, Kokkos::LayoutRight,
                   Kokkos::HostSpace,
                   Kokkos::Experimental::EmptyViewHooks>
          f,
      Kokkos::View<int *, Kokkos::LayoutRight,
                   Kokkos::HostSpace,
                   Kokkos::Experimental::EmptyViewHooks>
          type) :     use_stackparams(use_stackparams), 
    rnd_lj1(rnd_lj1), 
    rnd_lj2(rnd_lj2), 
    rnd_cutsq(rnd_cutsq), 
    num_neighs_view(num_neighs_view), 
    neighs_view(neighs_view), 
    x(x), 
    f(f), 
    type(type)  {
  };
  void operator()(const fullneigh_reduce_tag &, int i,
                                  double &PE) const ;
};

#endif